-- Carga de puntos de interés reales de Rosario.
-- Coordenadas verificadas con OpenStreetMap / Nominatim.
-- geom se construye con ST_SetSRID(ST_MakePoint(lon, lat), 4326).
-- Nota: ST_MakePoint toma (longitud, latitud) en ese orden.

TRUNCATE pois;

INSERT INTO pois (id, nombre, categoria, descripcion, tags, geom) VALUES
(1,  'Monumento Nacional a la Bandera', 'monumento',  'Conjunto monumental en honor a la creación de la bandera argentina por Manuel Belgrano. Mirador con vista al río Paraná.', ARRAY['histórico','vista al río','gratuito'], ST_SetSRID(ST_MakePoint(-60.6308, -32.9476), 4326)),
(2,  'Parque España',                   'parque',     'Espacio verde sobre la barranca del Paraná, con anfiteatro y paseos peatonales.',                                          ARRAY['espacio verde','río','familiar'],      ST_SetSRID(ST_MakePoint(-60.6352, -32.9399), 4326)),
(3,  'Estación Fluvial',                'turistico',  'Punto de partida de paseos en lancha por el río y las islas. Zona turística costera.',                                     ARRAY['río','paseos','gastronomía'],          ST_SetSRID(ST_MakePoint(-60.6264, -32.9493), 4326)),
(4,  'Mercado del Patio',               'gastronomia','Mercado gastronómico en una antigua estación ferroviaria recuperada.',                                                     ARRAY['gastronomía','patio de comidas','histórico'], ST_SetSRID(ST_MakePoint(-60.6696, -32.9399), 4326)),
(5,  'Museo Municipal Castagnino',      'museo',      'Principal museo de bellas artes de Rosario, con colección de arte argentino y europeo. Frente al Parque de la Independencia.', ARRAY['arte','cultura','museo'],            ST_SetSRID(ST_MakePoint(-60.6566, -32.9539), 4326)),
(6,  'Parque de la Independencia',      'parque',     'El parque más grande de la ciudad: lago, rosedal, museos y estadios.',                                                     ARRAY['espacio verde','lago','familiar'],     ST_SetSRID(ST_MakePoint(-60.6600, -32.9592), 4326)),
(7,  'Paseo del Siglo',                 'historico',  'Corredor de arquitectura de principios del siglo XX sobre calle Córdoba.',                                                 ARRAY['arquitectura','histórico','compras'],  ST_SetSRID(ST_MakePoint(-60.6470, -32.9460), 4326)),
(8,  'Catedral Basílica de Rosario',    'historico',  'Catedral de Nuestra Señora del Rosario, frente a la Plaza 25 de Mayo.',                                                    ARRAY['religioso','arquitectura','histórico'],ST_SetSRID(ST_MakePoint(-60.6323, -32.9475), 4326)),
(9,  'Plaza 25 de Mayo',                'historico',  'Plaza fundacional rodeada de edificios históricos y el Palacio de los Leones.',                                            ARRAY['plaza','histórico','centro'],          ST_SetSRID(ST_MakePoint(-60.6332, -32.9470), 4326)),
(10, 'Parque Urquiza',                  'parque',     'Parque costero con el Complejo Astronómico Municipal y planetario.',                                                       ARRAY['espacio verde','planetario','río'],    ST_SetSRID(ST_MakePoint(-60.6235, -32.9572), 4326)),
(11, 'MACRO - Museo de Arte Contemporáneo','museo',   'Museo de arte contemporáneo emplazado en antiguos silos de colores junto al río, en Puerto Norte.',                        ARRAY['arte','contemporáneo','río'],          ST_SetSRID(ST_MakePoint(-60.6506, -32.9301), 4326)),
(12, 'Estadio Gigante de Arroyito',     'deporte',    'Estadio de Rosario Central, sede de partidos y eventos masivos.',                                                          ARRAY['fútbol','deporte','eventos'],          ST_SetSRID(ST_MakePoint(-60.6745, -32.9140), 4326)),
(13, 'Boulevard Oroño',                 'historico',  'Avenida arbolada con palacetes y patrimonio arquitectónico de la ciudad.',                                                 ARRAY['arquitectura','paseo','histórico'],    ST_SetSRID(ST_MakePoint(-60.6566, -32.9468), 4326)),
(14, 'Balneario La Florida',            'turistico',  'Principal balneario sobre el río Paraná en el norte de la ciudad.',                                                        ARRAY['playa','río','verano'],                ST_SetSRID(ST_MakePoint(-60.6872, -32.8825), 4326)),
(15, 'La Granja de la Infancia',        'parque',     'Espacio recreativo y educativo para familias, parte del Tríptico de la Infancia.',                                        ARRAY['familiar','niños','naturaleza'],       ST_SetSRID(ST_MakePoint(-60.7255, -32.9767), 4326)),
(16, 'Acuario del Río Paraná',          'turistico',  'Acuario científico dedicado a la fauna del río Paraná, con sala de cría y especies autóctonas.',                          ARRAY['familiar','río','ciencia'],            ST_SetSRID(ST_MakePoint(-60.6751, -32.9112), 4326)),
(17, 'La Isla de los Inventos',         'turistico',  'Espacio lúdico y educativo en la antigua estación Rosario Central, parte del Tríptico de la Infancia.',                   ARRAY['familiar','niños','cultura'],          ST_SetSRID(ST_MakePoint(-60.6404, -32.9367), 4326)),
(18, 'Jardín de los Niños',             'parque',     'Parque temático y recreativo dentro del Parque de la Independencia, inspirado en el juego y la imaginación.',             ARRAY['familiar','niños','espacio verde'],    ST_SetSRID(ST_MakePoint(-60.6597, -32.9572), 4326)),
(19, 'Teatro El Círculo',               'historico',  'Teatro lírico de principios del siglo XX, célebre por su acústica y arquitectura italianizante.',                         ARRAY['teatro','arquitectura','histórico'],   ST_SetSRID(ST_MakePoint(-60.6351, -32.9526), 4326)),
(20, 'Plaza Montenegro',                'historico',  'Plaza céntrica rodeada de comercios y arquitectura tradicional, punto de encuentro del microcentro.',                     ARRAY['plaza','centro','histórico'],          ST_SetSRID(ST_MakePoint(-60.6378, -32.9497), 4326)),
(21, 'Museo de la Memoria',             'museo',      'Museo dedicado a la memoria, los derechos humanos y la última dictadura argentina.',                                      ARRAY['memoria','derechos humanos','cultura'],ST_SetSRID(ST_MakePoint(-60.6510, -32.9443), 4326)),
(22, 'Alto Rosario Shopping',           'turistico',  'Centro comercial sobre los terrenos del antiguo ferrocarril, con tiendas, cine y patio de comidas.',                      ARRAY['compras','cine','familiar'],           ST_SetSRID(ST_MakePoint(-60.6684, -32.9275), 4326)),
(23, 'Bar El Cairo',                     'gastronomia','Café histórico inmortalizado por Roberto Fontanarrosa y su "mesa de los galanes".',                                       ARRAY['café','histórico','literario'],        ST_SetSRID(ST_MakePoint(-60.6380, -32.9450), 4326)),
(24, 'Plaza Sarmiento',                 'historico',  'Plaza tradicional del centro rosarino, rodeada de edificios públicos y escuelas históricas.',                             ARRAY['plaza','centro','espacio verde'],      ST_SetSRID(ST_MakePoint(-60.6424, -32.9490), 4326)),
(25, 'Estadio Marcelo Bielsa',          'deporte',    'Estadio de Newell''s Old Boys, "El Coloso del Parque", dentro del Parque de la Independencia.',                            ARRAY['fútbol','deporte','eventos'],          ST_SetSRID(ST_MakePoint(-60.6614, -32.9561), 4326)),
(26, 'Anfiteatro Municipal Humberto de Nittis','historico','Anfiteatro al aire libre sobre la costa del Paraná, sede de espectáculos y festivales.',                            ARRAY['espectáculos','río','cultura'],        ST_SetSRID(ST_MakePoint(-60.6224, -32.9579), 4326));
